FlightManagement/Controllers/AirlinesController.cs
using FlightManagement.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FlightManagement.Controllers
{
    public class AirlinesController : Controller
    {
        DAPMEntities database = new DAPMEntities();
        // GET: Airlines
        public ActionResult Index()
        {
            var airAD = database.Airlines.ToList();
            return View(airAD);
        }
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "airlineID,airlineName,code")] Airline airline)
        {
            if (ModelState.IsValid)
            {
                // Ensure ID is not set to any value
                airline.airlineID = 0; // Not necessary if IDENTITY_INSERT is set to OFF

                database.Airlines.Add(airline);
                database.SaveChanges();
                TempData["SuccessMessage"] = "Tạo thành công!";
                return RedirectToAction("Index");
            }
            return View(airline);
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            Airline airline = database.Airlines.FirstOrDefault(p => p.airlineID == id);
            if (airline != null)
            {
                return View(airline);
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "airlineID,airlineName,code")] Airline airline)
        {
            if (ModelState.IsValid)
            {
                var airlineDB = database.Airlines.FirstOrDefault(p => p.airlineID == airline.airlineID);
                if (airlineDB != null)
                {
                    airlineDB.airlineName = airline.airlineName;
                    airlineDB.code = airline.code;

                    database.SaveChanges();
                    TempData["SuccessMessage"] = "Chỉnh sửa thành công!";
                    return RedirectToAction("Index");
                }
            }
            return View(airline);
        }


        [HttpGet]
        public ActionResult Delete(int id)
        {
            Airline airline = database.Airlines.FirstOrDefault(p => p.airlineID == id);
            if (airline != null)
                return View(airline);
            else return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(string id)
        {
            int i = int.Parse(id);
            var airlineDB = database.Airlines.FirstOrDefault(p => p.airlineID == i);
            if (airlineDB != null)
            {
                database.Airlines.Remove(airlineDB);
                TempData["SuccessMessage"] = "Xóa thành công!";
                database.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }
}

FlightManagement/Controllers/FlightsController.cs
using FlightManagement.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FlightManagement.Controllers
{
    public class FlightsController : Controller
    {
        DAPMEntities database = new DAPMEntities();
        // GET: Flights
        public ActionResult Index()
        {
            var flyAD = database.Flights.ToList();
            return View(flyAD);
        }
        [HttpGet]
        public ActionResult Create()
        {
            ViewBag.AircraftID = new SelectList(database.Aircraft, "aircraftID", "model");
            ViewBag.AirlineID = new SelectList(database.Airlines, "airlineID", "airlineName");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "flightID,flightNumber,departureCity,arrivalCity,departureTime,flightDuration,flightPrice,aircraftID, airlineID")] Flight flight)
        {
            if (ModelState.IsValid)
            {
                // Ensure ID is not set to any value
                flight.flightID = 0; // Not necessary if IDENTITY_INSERT is set to OFF

                database.Flights.Add(flight);
                database.SaveChanges();
                TempData["SuccessMessage"] = "Tạo thành công!";
                return RedirectToAction("Index");
            }
            ViewBag.AircraftID = new SelectList(database.Aircraft, "aircraftID", "model", flight.aircraftID);
             ViewBag.AirlineID = new SelectList(database.Airlines, "airlineID", "airlineName", flight.airlineID);
            return View(flight);
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            Flight flight = database.Flights.FirstOrDefault(p => p.flightID == id);
            if (flight != null)
            {
                ViewBag.AircraftID = new SelectList(database.Aircraft, "aircraftID", "model", flight.aircraftID);
                 ViewBag.AirlineID = new SelectList(database.Airlines, "airlineID", "airlineName", flight.airlineID);
                return View(flight);
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "flightID,departureCity,arrivalCity,departureTime,flightDuration,flightPrice,aircraftID,airlineID")] Flight flight)
        {
            if (ModelState.IsValid)
            {
                var flightDB = database.Flights.FirstOrDefault(p => p.flightID == flight.flightID);
                if (flightDB != null)
                {
                    flightDB.departureCity = flight.departureCity;
                    flightDB.arrivalCity = flight.arrivalCity;
                    flightDB.departureTime = flight.departureTime;
                    flightDB.flightDuration = flight.flightDuration;
                    flightDB.flightPrice = flight.flightPrice;
                    flightDB.aircraftID = flight.aircraftID;
                    flightDB.airlineID = flight.airlineID;

                    database.SaveChanges();
                    TempData["SuccessMessage"] = "Chỉnh sửa thành công!";
                    return RedirectToAction("Index");
                }
            }
            ViewBag.AircraftID = new SelectList(database.Aircraft, "aircraftID", "model", flight.aircraftID);
             ViewBag.AirlineID = new SelectList(database.Airlines, "airlineID", "airlineName", flight.airlineID);
            return View(flight);
        }


        [HttpGet]
        public ActionResult Delete(int id)
        {
            Flight flight = database.Flights.FirstOrDefault(p => p.flightID == id);
            if (flight != null)
                return View(flight);
            else return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(string id)
        {
            int i = int.Parse(id);
            var FlightDB = database.Flights.FirstOrDefault(p => p.flightID == i);
            if (FlightDB != null)
            {
                database.Flights.Remove(FlightDB);
                TempData["SuccessMessage"] = "Xóa thành công!";
                database.SaveChanges();
            }
            return RedirectToAction("Index");
        }
        public ActionResult Search()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Search(string departureCity, string arrivalCity, DateTime? departureTime)
        {
            // Lấy danh sách chuyến bay từ cơ sở dữ liệu
            var flightList = database.Flights.AsQueryable(); // AsQueryable() cho phép linh hoạt với các truy vấn

            // Lọc theo thành phố khởi hành
            if (!string.IsNullOrEmpty(departureCity))
            {
                flightList = flightList.Where(x => x.departureCity == departureCity);
            }

            // Lọc theo thành phố đến
            if (!string.IsNullOrEmpty(arrivalCity))
            {
                flightList = flightList.Where(x => x.arrivalCity == arrivalCity);
            }

            // Lọc theo thời gian khởi hành
            if (departureTime.HasValue)
            {
                flightList = flightList.Where(x => x.departureTime.Date == departureTime.Value.Date);
            }

            return View("Search", flightList.ToList());
        }
    }
}

FlightManagement/Controllers/PaymentController.cs
using FlightManagement.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FlightManagement.Controllers
{
    public class PaymentController : Controller
    {
        DAPMEntities database = new DAPMEntities();

        // GET: Aircrafts
        public ActionResult Index()
        {
            var payAD = database.Payments.ToList();
            return View(payAD);
        }

        [HttpGet]
        public ActionResult Create()
        {
            ViewBag.BookingID = new SelectList(database.Bookings, "bookingID", "bookingDate"); // Assuming 'airlines' table has 'airlineID' and 'airlineName'
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "paymentID,amount,paymentDate,paymentMethod,status,bookingID")] Payment payment)
        {
            if (ModelState.IsValid)
            {
                // Ensure ID is not set to any value
                payment.paymentID = 0; // Not necessary if IDENTITY_INSERT is set to OFF

                database.Payments.Add(payment);
                database.SaveChanges();
                TempData["SuccessMessage"] = "Tạo thành công!";
                return RedirectToAction("Index");
            }
            ViewBag.BookingID = new SelectList(database.Bookings, "bookingID", "bookingDate", payment.bookingID); // Ensure correct ViewBag key
            return View(payment);
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            Payment payment = database.Payments.FirstOrDefault(p => p.paymentID == id);
            if (payment != null)
            {
                ViewBag.BookingID = new SelectList(database.Bookings, "bookingID", "bookingDate", payment.bookingID); // Ensure correct ViewBag key
                return View(payment);
            }
            else
                return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "paymentID,amount,paymentDate,paymentMethod,status,bookingID")] Payment payment)
        {
            if (ModelState.IsValid)
            {
                var paymentDB = database.Payments.FirstOrDefault(p => p.paymentID == payment.paymentID);
                if (paymentDB != null)
                {
                    paymentDB.amount = payment.amount;
                    paymentDB.paymentDate = payment.paymentDate;
                    paymentDB.paymentMethod = payment.paymentMethod;
                    paymentDB.status = payment.status;
                    paymentDB.bookingID = payment.bookingID;

                    database.SaveChanges();
                    TempData["SuccessMessage"] = "Chỉnh sửa thành công!";
                    return RedirectToAction("Index");
                }
            }
            ViewBag.BookingID = new SelectList(database.Bookings, "bookingID", "bookingDate", payment.bookingID); // Ensure correct ViewBag key
            return View(payment);
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            Payment payment = database.Payments.FirstOrDefault(p => p.paymentID == id);
            if (payment != null)
            {
                return View(payment);
            }
            else return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(string id)
        {
            int i = int.Parse(id);
            var payDB = database.Payments.FirstOrDefault(p => p.paymentID == i);
            if (payDB != null)
            {
                database.Payments.Remove(payDB);
                TempData["SuccessMessage"] = "Xóa thành công!";
                database.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }
}

FlightManagement/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background-color: #f0f2f5;
            color: #333;
            display: flex;
            min-height: 100vh;
            margin: 0;
        }

        .sidebar {
            width: 220px;
            padding-left: 20px;
            background-color: #ffffff;
            box-shadow: 2px 0 5px rgba(0, 0, 0, 0.1);
            display: flex;
            flex-direction: column;
            justify-content: space-between;
            position: fixed;
            height: 100%;
            overflow-y: hidden;
            border-top-right-radius: 20px;
            border-bottom-right-radius: 20px;
        }

            .sidebar:hover {
                overflow-y: auto;
            }

            .sidebar .logo {
                display: block;
                text-align: center;
            }

                .sidebar .logo img {
                    max-width: 100%;
                    height: auto;
                }

            .sidebar ul {
                list-style: none;
                padding: 0;
                margin: 0;
            }

            .sidebar li {
                width: 100%;
            }

            .sidebar a {
                display: flex;
                align-items: center;
                padding: 10px 20px;
                color: #77dada;
                text-decoration: none;
                transition: all 0.3s ease;
                border-top-left-radius: 25px;
                border-bottom-left-radius: 25px;
            }

                .sidebar a .icon {
                    margin-right: 10px;
                    font-size: 1.5em;
                    width: 30px;
                    height: 30px;
                }

                .sidebar a:hover:not(.logo a), .sidebar a.active {
                    background-color: #77dada;
                    color: #ffffff;
                }

        .main-content {
            flex: 1;
            padding: 20px;
            overflow: auto;
            margin-left: 220px;
        }

        footer {
            background-color: #ffffff;
            padding: 20px;
            box-shadow: 0 -4px 6px rgba(0, 0, 0, 0.1);
            text-align: center;
        }

        .small-box {
            background: #ffffff;
            border-radius: 0.25rem;
            box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
            color: #333;
            display: block;
            margin-bottom: 20px;
            overflow: hidden;
            padding: 20px;
            position: relative;
        }

            .small-box h3 {
                font-size: 2.2em;
                font-weight: bold;
                margin: 0;
                padding: 0;
                text-overflow: ellipsis;
                white-space: nowrap;
            }

            .small-box p {
                font-size: 1.2em;
            }

            .small-box .icon {
                color: rgba(0, 0, 0, 0.15);
                font-size: 4.5em;
                position: absolute;
                right: 10px;
                top: 10px;
                z-index: 0;
            }

            .small-box .small-box-footer {
                background: rgba(0, 0, 0, 0.15);
                color: #ffffff;
                display: block;
                padding: 10px 0;
                text-align: center;
                text-decoration: none;
                z-index: 10;
            }

                .small-box .small-box-footer:hover {
                    background: rgba(0, 0, 0, 0.15);
                }

        .bg-primary {
            background-color: #007bff !important;
            color: #fff !important;
        }

        .bg-secondary {
            background-color: #6c757d !important;
            color: #fff !important;
        }

        .bg-info {
            background-color: #17a2b8 !important;
            color: #fff !important;
        }

        .bg-warning {
            background-color: #ffc107 !important;
            color: #fff !important;
        }

        .bg-success {
            background-color: #28a745 !important;
            color: #fff !important;
        }

        .bg-danger {
            background-color: #dc3545 !important;
            color: #fff !important;
        }

        .chart-row {
            margin-bottom: 20px;
        }
    </style>
</head>
<body>
    <nav class="sidebar">
        <div>
            <div class="logo">
                <a>
                    <img src="~/Content/Image/logo.png" alt="Logo">
                </a>
            </div>
            <ul>
                <li><a href="@Url.Action("Index", "Login")" class="@((ViewContext.RouteData.Values["controller"].ToString() == "Accounts") ? "active" : "")"><i class="fas fa-user icon"></i> Account</a></li>
                <li><a href="@Url.Action("Index", "Airlines")" class="@((ViewContext.RouteData.Values["controller"].ToString() == "Airlines") ? "active" : "")"><i class="fas fa-plane icon"></i> Airline</a></li>
                <li><a href="@Url.Action("Index", "Aircrafts")" class="@((ViewContext.RouteData.Values["controller"].ToString() == "Aircrafts") ? "active" : "")"><i class="fas fa-plane-departure icon"></i> Aircraft</a></li>
                <li><a href="@Url.Action("Index", "Flights")" class="@((ViewContext.RouteData.Values["controller"].ToString() == "Flights") ? "active" : "")"><i class="fas fa-fighter-jet icon"></i> Flight</a></li>
                <li><a href="@Url.Action("Index", "Booking")" class="@((ViewContext.RouteData.Values["controller"].ToString() == "Bookings") ? "active" : "")"><i class="fas fa-book icon"></i> Booking</a></li>
                <li><a href="@Url.Action("Index", "Payment")" class="@((ViewContext.RouteData.Values["controller"].ToString() == "Payments") ? "active" : "")"><i class="fas fa-credit-card icon"></i> Payments</a></li>               <li class="Header_menu__jRq_R h-full flex align-center" style="margin-left: 10px">
                    <a href="javascript:void(0);" onclick="confirmLogout();" class="md"><i class="fas fa-sign-out-alt"></i> Đăng Xuất</a>
                </li>

            </ul>
        </div>
    </nav>
    <div class="main-content">
        @RenderBody()
    </div>
    <script>
    function confirmLogout() {
    if (confirm("Bạn có muốn đăng xuất không?")) {
        window.location.href = "@Url.Action("Login", "Login")";
    }
}
    </script>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

FlightManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="main-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

FlightManagement/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <style>
        .video-background {
            position: fixed;
            right: 0;
            bottom: 0;
            min-width: 100%;
            min-height: 100%;
            z-index: -1;
        }
    </style>
    }
    <video autoplay muted loop class="video-background">
        <source src="~/Content/Background.mp4" type="video/mp4">
    </video>
    <div>
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>